version: '3.5'

services:
  torproxy:
    image: bunseokbot/torproxy:latest
    container_name: torproxy
    networks:
      - darklight

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: darklight:latest
    container_name: scheduler
    environment:
      - CONFIG_FILE=config.ini
    networks:
      - darklight
      - database

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: darklight:latest
    container_name: worker
    command: ["celery", "worker", "-A", "crawler.tasks", "--autoscale=1,7"]
    environment:
      - CONFIG_FILE=config.ini
    networks:
      - darklight
      - database

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - darklight

networks:
  darklight:
    name: darklight
  database:
    external:
      name: database
